### ISSUE TITLE
Prevent multiple sessions from editing the same scenario at the same time

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/scenario-editor#100]
- [x] Timeout inactive sessions
- [ ] Flag/disallow editing a scenario/modification that has recently been edited by another session

**Comment by trevorgerhardt** [comment]
@mattwigway is there a "last edited" user associated with scenarios and modifications?

**Comment by mattwigway** [comment]
There is not, but also we want to prevent the same user from editing in
multiple tabs.

On Mon, Jun 27, 2016 at 7:26 PM, Trevor Gerhardt <notifications@github.com>
wrote:

> @mattwigway <https://github.com/mattwigway> is there a "last edited" user
> associated with scenarios and modifications?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/conveyal/scenario-editor/issues/100#issuecomment-228905976>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAimrhrLlVgCIX5ArIh49BufOlv4crGVks5qQFwogaJpZM4Imog5>
> .
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Comment by trevorgerhardt** [comment]
I guess we can compare timestamps. "Last edited at". Then when saving to the server, it can see if the timestamps match up, if not, don't save and warn the user that their data is out of date. Thoughts?

**Comment by mattwigway** [comment]
That's a pretty standard way to do it, and seems reasonable.

**Comment by trevorgerhardt** [comment]
Cool, that's should be a pretty simple change on the backend with just a way to show a clear error about what happened on the front end. Want to implement the backend portion and when that's done I'll change the front?

**Comment by mattwigway** [comment]
I think that we have fixed this so that multiple editing will not cause disastrous results - no modifications will be overwritten, although it's possible that deletes will not work if the other session resaves that modification, and new modifications may not propagate until page reload, but there's no longer a huge issue.
