### ISSUE TITLE
slow interface when a lot of modifications are active

### ISSUE THREAD

**Issue by MarcovanderLinden** [conveyal/scenario-editor#106]
When a lot of modifications are visible and/or expanded, the interface gets so slow that it gets hard to work with.

**Comment by abyrd** [comment]
I can vouch for this, working on the Netherlands scenarios. The interface is extremely slow to the point that it basically isn't usable. Not just when modifying anything, but all the time. Simply scrolling through the modifications or panning the map is almost impossible.

I did some profiling but didn't see anything obvious eating processor time. @trevorgerhardt or @mattwigway do we have some theory as to what's causing this?

**Comment by mattwigway** [comment]
We made some rendering changes, I've been working with enormous scenarios without issue.
