### ISSUE TITLE
Variants can disappear

### ISSUE THREAD

**Issue by mattwigway** [conveyal/scenario-editor#112]
Sometimes all the variants for a project will just disappear. I suspect we're saving the project before it's finished loading.

**Comment by trevorgerhardt** [comment]
Does this still happen?

**Comment by mattwigway** [comment]
Well I did this: https://github.com/conveyal/scenario-editor/commit/cf56cfc4b563ed497e421bb31b566644d0a9db49 as a workaround.

That's a stopgap. I'm not sure if the underlying problem has been fixed; it seemed to happen very occasionally and randomly.
