### ISSUE TITLE
Specify bundle at project creation time

### ISSUE THREAD

**Issue by mattwigway** [conveyal/scenario-editor#116]
When you create a project you should have to choose a bundle, and after that you should not be able to change that bundle. Changing bundles mid-stream, while not as damply hazardous as changing horses mid-stream, is asking for trouble.

**Comment by trevorgerhardt** [comment]
So a project should always have the same bundle id? The current UI should definitely be reworked then.

**Comment by trevorgerhardt** [comment]
Also, when you import a shapefile, you're importing modifications to apply to a project -> bundle combination correct?

**Comment by trevorgerhardt** [comment]
Cause then we have two ways to "import modifications and apply to project".
