### ISSUE TITLE
While uploading feed, error dialog appears repeatedly

### ISSUE THREAD

**Issue by abyrd** [conveyal/scenario-editor#118]
While uploading a feed to the scenario editor the following dialog box appears:
![image](https://cloud.githubusercontent.com/assets/112871/16216858/97ac4d7c-376e-11e6-8199-1e04b42af230.png)

When the dialog box is dismissed it just keeps reappearing indefinitely.

**Comment by abyrd** [comment]
Same problem occurs on Firefox, creating a bundle before selecting any project.

**Comment by abyrd** [comment]
JS console trace:

```
index.js:10310 Error: Not Found
    at parseJSON (https://s3.amazonaws.com/scenario-editor/assets/index.js:10414:11) "Error: Not Found
    at parseJSON (https://s3.amazonaws.com/scenario-editor/assets/index.js:10414:11)"(anonymous function) @ index.js:10310
https://scenario-editor.conveyal.com/api/bundle/36a623c188514c06a93855d6fba3f50e Failed to load resource: the server responded with a status of 404 (Not Found)
```

The API seems to be responding with a 401 unauthorized.

**Comment by abyrd** [comment]
This happens even on a newly created Auth0 user assigned to a new empty group.

**Comment by mattwigway** [comment]
This is because the bundle doesn't appear in the database until the GTFS is processed. It is fixed in master.

**Comment by trevorgerhardt** [comment]
Read this as fixed, closing
