### ISSUE TITLE
When uploading feed, "uploading" spinner spins forever

### ISSUE THREAD

**Issue by abyrd** [conveyal/scenario-editor#119]
For at least several minutes after the outgoing network usage dropped to zero, the "uploading..." spinner just keeps spinning. Nothing appears to be happening.

![image](https://cloud.githubusercontent.com/assets/112871/16217097/ce16edc0-3770-11e6-93e0-38dcc1283b8e.png)

**Comment by mattwigway** [comment]
This is likely due to an exception in the GTFS load process. There is code in master to report the error, but it has not been tested.

**Comment by abyrd** [comment]
I'm still running into problems uploading files. Now the error is reported but it's not very informative, and dismissing the dialog causes it to re-appear repeatedly. I think we determined that the error might be caused by trips that have only one stop.

![image](https://cloud.githubusercontent.com/assets/112871/16764849/4b33bfce-4863-11e6-8e87-b4e14f5c488e.png)

**Comment by abyrd** [comment]
Should we be moving technical tickets like this into Asana @trevorgerhardt and @mattwigway ?

**Comment by mattwigway** [comment]
Is that on production? Production is rubbing very old code; I'm hoping to
get everything moved over today but I'm having trouble with our database
provider.

**Comment by abyrd** [comment]
Yes, on production. I didn't realize it was old code, just let me know when you get a chance to update it.

**Comment by trevorgerhardt** [comment]
@abyrd I'd say while we're migrating we can continue to discuss and use GH while there are still tickets here, but only open new ones on Asana

**Comment by abyrd** [comment]
Makes sense @trevorgerhardt. Maybe if something's high priority and we don't want to forget about it we can tolerate some duplicates in Asana.
