### ISSUE TITLE
Require login

### ISSUE THREAD

**Issue by mattwigway** [conveyal/scenario-editor#37]
Currently the app comes up even when the user is not logged in. Now that the backend requires auth, this is confusing, as the user can't do anything with the app because all requests to the backend fail. We should check if the user is logged in, and make them log in if they aren't.

**Comment by trevorgerhardt** [comment]
In the future, will we want this to be able to run in "standalone"/"local" mode?

**Comment by trevorgerhardt** [comment]
I could see it being useful to allow the Scenario Editor + Analyst to run together without Auth

**Comment by trevorgerhardt** [comment]
Basically IF Auth0 credentials are provided, require it. If not, go cray

**Comment by mattwigway** [comment]
Yeah probably not a bad idea. Can we make it a config param?

On Thu, Mar 31, 2016 at 4:40 PM, Trevor Gerhardt <notifications@github.com>
wrote:

> I could see it being useful to allow the Scenario Editor + Analyst to run
> together without Auth
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/scenario-editor/issues/37#issuecomment-204116838>
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC

**Comment by mattwigway** [comment]
cool cool

On Thu, Mar 31, 2016 at 4:40 PM, Trevor Gerhardt <notifications@github.com>
wrote:

> Basically IF Auth0 credentials are provided, require it. If not, go cray
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/scenario-editor/issues/37#issuecomment-204116988>
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC
