### ISSUE TITLE
Change show/hide buttons to an eye icon

### ISSUE THREAD

**Issue by abyrd** [conveyal/scenario-editor#54]
This seems to be the standard in photoshop etc.
![image](https://cloud.githubusercontent.com/assets/112871/14384690/b0bb0986-fd9c-11e5-9389-f71db0705524.png)

We seem to already have a good eye icon in analyst-server:
![image](https://cloud.githubusercontent.com/assets/112871/14384730/e136cb90-fd9c-11e5-8007-e3df91b4fcdd.png)

**Comment by mattwigway** [comment]
I think I've got this right:

Shown: 
![image](https://cloud.githubusercontent.com/assets/566958/14394635/37525c80-fd9b-11e5-831a-91a135eaeffe.png)

Hidden: 
![image](https://cloud.githubusercontent.com/assets/566958/14394650/488210ea-fd9b-11e5-8e57-c60db8e09b4a.png)

**Comment by mattwigway** [comment]
Or maybe the icon should be not for the current state, but the state that the layer will be in if you click that button?

**Comment by trevorgerhardt** [comment]
After using it, I like the current implementation. The blue definitely feels like the modification should be showing on the map.

**Comment by mattwigway** [comment]
@trevorgerhardt how do you feel though about the icons? notice one is an eye, and one is an eye with a slash through it.

**Comment by trevorgerhardt** [comment]
Yea, I like the icons. I meant the current implementation with the eyes.

**Comment by mattwigway** [comment]
Eye eye sir.

On Mon, Apr 11, 2016 at 3:38 PM, Trevor Gerhardt <notifications@github.com>
wrote:

> Yea, I like the icons. I meant the current implementation with the eyes.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/conveyal/scenario-editor/issues/54#issuecomment-208520702>
>



-- 
Matthew Wigginton Conway [WIG-in-tun CON-way]
Transportation Analytics/Open Source
Washington, DC
