### ISSUE TITLE
Adjust-frequency should preview patterns

### ISSUE THREAD

**Issue by abyrd** [conveyal/scenario-editor#60]
When adjusting frequencies, we need to choose a trip from a typical pattern on the route. While stepping through the patterns, the map display does not change making it hard to see which one is the most typical pattern.

**Comment by mattwigway** [comment]
See also #25 - we either need to implement hover or come up with a better way. @trevorgerhardt rightly points out that hover won't work on tablets, and that's a definite use case for this app (or touch tables, in a public meeting context).

**Comment by abyrd** [comment]
Confirmed, I've had strong and specific requests to make everything work on tablets.
