### ISSUE TITLE
Import GTFS, decipher branching

### ISSUE THREAD

**Issue by mattwigway** [conveyal/scenario-editor#7]
We need to import GTFS routes and convert them to frequencies. @abyrd and I discussed this late last week, and we concluded that what we would do would be to identify branches, compute a frequency on each, and try to determine if there is intentional/consistent phasing between them.

**Comment by mattwigway** [comment]
After further discussion with @abyrd we have determined that there is no reason to try to decipher anything. We just show all the patterns and let the user figure out what goes together.

**Comment by abyrd** [comment]
Yes, we even decided we should always ask whether we're taking automation too far before making the computer guess what people are trying to accomplish. We should put the effort into clearly showing the user what patterns / objects exist and let them choose.
