### ISSUE TITLE
Selected pattern segments hard to see

### ISSUE THREAD

**Issue by abyrd** [conveyal/scenario-editor#78]
When creating an adjust-speed modification, it is difficult to see which segment of the patterns is selected, simply because of the colors used (dark purple on dark green).

**Comment by mattwigway** [comment]
![image](https://cloud.githubusercontent.com/assets/566958/14796177/ffa8d87e-0af9-11e6-9c1b-6d0ac7153682.png)

@abyrd better?

**Comment by abyrd** [comment]
So here you've selected patterns in both directions? Yes looks great!
