### ISSUE TITLE
data usage of the scenario editor.

### ISSUE THREAD

**Issue by MarcovanderLinden** [conveyal/scenario-editor#93]
The IT department of Movares warned me because I was using a lot of data yesterday. Our office in Rotterdam has a 20mb connection and for the hour I was editing yesterday i used almost all of that bandwith for the entire hour. Is it possible to make the editor available offline or at least with less dependency on the connection? It is no problem if I initially have to download a large file, but it is a problem if I constantly use all the available bandwith.

**Comment by abyrd** [comment]
Hi @MarcovanderLinden, can you clarify the bandwidth of the connection and how much your editing activity was using? Do you mean 20 megabits/second? That would be almost 2.5 megabytes per second over the course of the hour, which is indeed pretty high data usage.

**Comment by MarcovanderLinden** [comment]
Hi @abyrd, I've attached a file which shows the data usage in Rotterdam and a picture of the percentage going to an amazon server (which they determined came from my computer).
It shows an 20M connection, though I'm not completely sure what that means, but I hope you will.

Thereby it might be interesting to know that I was at this time deleting a lot of lines. I tried toggling the visiblity, but that did not change the speed of the programm (I noticed the programm slowed down as well). please let me know if you need more information.

[hrshaper_ PacketShaper Statistics Report.pdf](https://github.com/conveyal/scenario-editor/files/274404/hrshaper_.PacketShaper.Statistics.Report.pdf)
![image](https://cloud.githubusercontent.com/assets/19469753/15425403/54f3dff8-1e88-11e6-9738-1e2b12a2c424.png)

**Comment by abyrd** [comment]
Thanks @MarcovanderLinden this is very useful information.

**Comment by abyrd** [comment]
The specific process that was causing problems: Marco was creating remove-trips modifications and was seeing a lot of lag after selecting a route but before the appearance of the patterns. The problem appeared when Marco had created about 5 remove-trips modifications but he needs to delete about 100 routes in total. He noticed that some of the modifications were showing pattern lists and others were not (probably waiting on network responses. Only the appearance of patterns was slow but the rest of the interface remained responsive.

**Comment by mattwigway** [comment]
It looks like at some point we made a change so that all modifications and the project are saved every time anything is changed. This is probably the root cause of #100 as well: it was taking so long that someone closed the page before everything had saved.

**Comment by mattwigway** [comment]
OK, we no longer save all the modifications every time anything changes in the UI, which will significantly help this situation. However, it also appears the client side caches of transit data from the GTFS API are not working correctly; it's fetching data much more often than it needs to.
