### ISSUE TITLE
Download scenarios directly

### ISSUE THREAD

**Issue by mattwigway** [conveyal/scenario-editor#96]
Right now, choosing to download a scenario opens up the JSON in a new tab. It should instead just download the JSON. I know @abyrd had initially requested the current behavior, so maybe we need to retain that as well. @abyrd, comments?

**Comment by abyrd** [comment]
Under different circumstances we need to do both. Downloading the JSON seems like a stopgap as much as opening it in a new tab. Ideally we should be working on integrating the two tools (put the scenarios on S3?)

**Comment by mattwigway** [comment]
They're integrated! Woohoo!!!
