### ISSUE TITLE
Editing complex reroute is difficult due to tangle of routes

### ISSUE THREAD

**Issue by mattwigway** [conveyal/scenario-editor#97]
When we make a reroute in the middle of a line, the scenario editor by default connects the start and end stops with a straight line, which you can then drag to change the routing. When you have a complex reroute this can become very complex with a tangle of lines crossing each other. It might be wise to have a way to start from scratch and draw the line rather than having to drag the existing line.

**Comment by mattwigway** [comment]
Street following (#1) will help a lot, because once you drag a few points much of the reroute will just snap into place.

**Comment by trevorgerhardt** [comment]
Added street following in e8114fb37f061b4ab671a7de820205a6f459de84

**Comment by mattwigway** [comment]
I haven't observed this to be an issue and I've been creating some pretty extensive scenarios, so I'm going to go ahead and close.
